### ISSUE TITLE
Directly opening Harlequin keybindings results in "too many redirects"

### ISSUE THREAD

**Issue by MartinBernstorff** [tconbeer/harlequin-web#83] opened 2024-05-03 06:44 UTC
If I click the link in the readme, or go directly to https://harlequin.sh/docs/bindings, Chrome shows me a: 
<img width="780" alt="image" src="https://github.com/tconbeer/harlequin/assets/8526086/b6737d37-2373-401c-81be-efd3f9dd9508">

However, if I navigate to https://harlequin.sh and navigate to the bindings, no issue.

I haven't repro'd on other devices, so if you can't repro, feel free to close 👍

**Comment by tconbeer** [comment] 2024-05-03 20:39
I think this is https://github.com/sveltejs/kit/issues/10155, which is caused by ISR, which I recently configured. Looks like it was fixed in https://github.com/sveltejs/kit/pull/11928, which was included in `@sveltejs/adapter-vercel@5.1.1`. I'm running v3.0.3, so maybe an upgrade will fix...

**Comment by tconbeer** [comment] 2024-05-03 20:52
Fixed now. Thanks so much for the report! I don't think I would have found this for quite a while

**Closed** 2024-05-03 20:51 UTC
Labels: bug
